### ISSUE TITLE
Вы указали в pom.xml версию 12, а в Travis у вас стоит 11

### ISSUE THREAD

**Issue by coursar** [idris-musin/Library#3]
https://github.com/idris-musin/Library/blob/b068387f24bc587fc8423a69db03516a6536e6a2/.travis.yml#L2

**Comment by idris-musin** [comment]
Все равно не компилится в travis. Выдается такая ошибка: 

![image](https://user-images.githubusercontent.com/47304496/55509149-22ad1e80-5664-11e9-9771-94bd3d6fe655.png)

**Comment by coursar** [comment]
Теперь он вам ругается на JaCoCo, поскольку вы совсем убрали правила по покрытию, JaCoCo не понимает, что он должен проверять.

Вот эти строки вырежьте:
https://github.com/idris-musin/Library/blob/cb704feb77e2bfc28f5e88150914f2c7ec60d563/pom.xml#L34-L39

Кроме того, вы можете запустить verify локально, не обязательно ждать для этого Travis

**Comment by idris-musin** [comment]
Исправлено

**Comment by coursar** [comment]
Зачем тогда открывать issue?
